### ISSUE TITLE
ReferenceError: Cannot access 'setupURL' before initialization

### ISSUE THREAD

**Issue by jdrin** [rowyio/rowyrun#1]
Setup URL cannot be accessed and isn't displayed.

ReferenceError in Cloud Shell when running command: node hooks/postcreate.mjs

> ReferenceError: Cannot access 'setupURL' before initialization
>     at start (file:///home/***/rowyrun/hooks/postcreate.mjs:18:22)
>     at processTicksAndRejections (internal/process/task_queues.js:97:5)

- rowy-backend
- rowy-hooks
- rowy-deploy

All successfully deploy.

rowy-deploy URL is displayed.

**Comment by jdrin** [comment]
Apologies - Issue did not replicate when using a new Firebase Project. Closing the issue and will update if I come across the setting responsible.
